version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/postgres"
      - "/mysql"
      - "/middleware/echo"
      - "/middleware/gin"
      - "/middleware/nethttp"
    reviewers:
      - "bartventer"
    assignees:
      - "bartventer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    commit-message:
      prefix: "fix"
      include: "scope"

  - package-ecosystem: "gomod"
    directory: "/examples"
    assignees:
      - "bartventer"
    reviewers:
      - "bartventer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    assignees:
      - "bartventer"
    reviewers:
      - "bartventer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    commit-message:
      prefix: "ci"
      include: "scope"

  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer/build"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    commit-message:
      prefix: "chore"
      include: "scope"
