version: 2
updates:
    - package-ecosystem: 'gomod'
      directory: '/'
      schedule:
          interval: 'weekly'
      commit-message:
          prefix: 'chore(deps)'
    - package-ecosystem: 'gomod'
      directory: '/examples/echo'
      schedule:
          interval: 'weekly'
      commit-message:
          prefix: 'chore(example-deps)'
    - package-ecosystem: 'gomod'
      directory: '/examples/nethttp'
      schedule:
          interval: 'weekly'
      commit-message:
          prefix: 'chore(example-deps)'
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
