version: 2
updates:
    - package-ecosystem: 'gomod'
      directory: '/'
      reviewers:
          - bartventer
      assignees:
          - bartventer
      schedule:
          interval: 'weekly'
      commit-message:
          prefix: 'fix(deps)'

    - package-ecosystem: 'gomod'
      directory: '/examples/echo'
      schedule:
          interval: 'weekly'
      commit-message:
          prefix: 'chore(examples/deps)'

    - package-ecosystem: 'gomod'
      directory: '/examples/nethttp'
      schedule:
          interval: 'weekly'
      commit-message:
          prefix: 'chore(examples/deps)'

    - package-ecosystem: 'github-actions'
      directory: '/'
      assignees:
          - bartventer
      reviewers:
          - bartventer
      commit-message:
          prefix: 'ci(workflows/deps)'
      schedule:
          interval: 'weekly'
