codecov:
  disable_default_path_fixes: true

coverage:
  status:
    project:
      default:
        target: 0
        threshold: "0%"
        base: auto
    patch:
      default:
        target: 0
        threshold: "0%"
        base: auto

ignore:
  - "**/_examples/**"
  - "**/pkg/drivertest/*"

fixes:
  - "github.com/bartventer/gorm-multitenancy/v8/::"
  - "github.com/bartventer/gorm-multitenancy/mysql/v8/::mysql/"
  - "github.com/bartventer/gorm-multitenancy/postgres/v8/::postgres/"
  - "github.com/bartventer/gorm-multitenancy/middleware/echo/v8/::middleware/echo/"
  - "github.com/bartventer/gorm-multitenancy/middleware/gin/v8/::middleware/gin/"
  - "github.com/bartventer/gorm-multitenancy/middleware/iris/v8/::middleware/iris/"
  - "github.com/bartventer/gorm-multitenancy/middleware/nethttp/v8/::middleware/nethttp/"
