name: Benchmark

on:
    workflow_dispatch: 
    workflow_run:
        workflows: ['Build']
        types:
            - completed

jobs:
    benchmark:
        name: Benchmark
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
        permissions: 
            contents: write # Grant permission to read and write repository contents
            pull-requests: write # Grant permission to create pull requests
            issues: write # Grant permission to write issues
        steps:
            - uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.22.x

            - name: Run benchmarks
              shell: bash
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  make benchmark
                  make update_readme