name: Benchmark

on:
    workflow_dispatch: 
    workflow_run:
        workflows: ['Build']
        types:
            - completed

jobs:
    benchmark:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
        steps:
            - uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.22.x

            - name: Run benchmarks
              shell: bash
              run: |
                  make benchmark
                  make update_readme