name: Benchmark

on:
    workflow_dispatch: 
    push:
        branches:
            - master

jobs:
    benchmark:
        name: Benchmark
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup-go
              with:
                  go-version: '1.22.x'

            - name: Run benchmarks
              run: make benchmark