name: Benchmark

on:
    workflow_dispatch: 
    push:
        branches:
            - master

jobs:
    benchmark:
        name: Benchmark
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.22.x

            - name: Run benchmarks
              run: make benchmark