name: Tests

on:
    push:
        branches: [master]
    pull_request:

jobs:
    test:
        name: Test
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                go-version: [1.22.x, 1.23.x, 1.24.x]
                include:
                    - go-version: 1.24.x
                      upload-coverage: true

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup-go
              with:
                  go-version: ${{ matrix.go-version }}

            - name: Build
              shell: bash
              run: make build

            - name: Test and Coverage
              shell: bash
              env:
                  UPLOAD_COVERAGE: ${{ matrix.upload-coverage }}
                  COVERPROFILE: ./cover.out
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
              run: make test
