name: Build

on:
    push:
        branches: [master]
    pull_request:

jobs:
    build:
        name: Build
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                go-version: [1.21.x, 1.22.x]
                include:
                    - go-version: 1.22.x
                      upload-coverage: true

        runs-on: ${{ matrix.os }}
        env:
            COVERPROFILE: ./cover.out
            COVERDIR: ${{ github.workspace }}/.cover
        steps:
            - uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: ${{ matrix.go-version }}

            - name: Build
              shell: bash
              run: make build

            - name: Test and Coverage
              shell: bash
              id: test
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
              run: |
                  make test

    license-scan:
        name: License scan
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        needs: [build]
        steps:
            - uses: actions/checkout@v4
            - name: Install FOSSA
              run: |
                  curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash

            - name: Run FOSSA analysis
              env:
                  FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
              run: fossa analyze

            - name: Check FOSSA status
              env:
                  FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
              run: fossa test
