name: Devcontainer Build

on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * 0' # Every Sunday at 00:00
    push:
        branches:
            - master
        paths:
            - '.devcontainer/build/**'

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: yarn global add @devcontainers/cli

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build, Push and Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: ./scripts/devcontainer.sh
