name: Lint

on:
    push:
        branches: [master]
    pull_request:

jobs:
    golangci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: ./.github/actions/setup-go
              with:
                  go-version: '1.23.x'

            - name: Run golangci-lint
              uses: golangci/golangci-lint-action@v6
              with:
                  version: v1.58.1
