name: Release

on:
    workflow_dispatch:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"
            - "[a-z]+/v[0-9]+.[0-9]+.[0-9]+"
    workflow_run:
        workflows: ["Tests"]
        branches: [master]
        types: [completed]

jobs:
    semantic-release:
        name: Semantic Release
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
        strategy:
            fail-fast: false
            max-parallel: 1
            matrix:
                directory:
                    - "."
                    - "postgres"
                    - "mysql"
                    - "middleware/echo"
                    - "middleware/gin"
                    - "middleware/nethttp"
        permissions:
            contents: write
            issues: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v2
              with:
                  check-latest: true
                  node-version: ">=22"
                  cache: "yarn"
                  cache-dependency-path: |
                    ${{ github.workspace }}/yarn.lock
                    ${{ github.workspace }}/package.json
            - name: 'Run semantic-release in "${{ matrix.directory }}"'
              working-directory: ${{ matrix.directory }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  cp ${{ github.workspace }}/yarn.lock ${{ github.workspace }}/package.json .
                  yarn install --modules-folder ${{ github.workspace }}/node_modules
                  npx semantic-release
