name: Bump version and Push tag

on:
  push:
    branches:
      - master

jobs:
  push:
    name: Bump version and Push tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          token: ${{ secrets.GH_PAT }}

      - name: Bump version and Push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: ${{ steps.tag_version.outputs.new_tag }}
          draft: false
          prerelease: false
