name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at 00:00

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write # To close stale issues
      pull-requests: write # To close stale pull requests

    steps:
      - uses: actions/stale@v9
        env:
          DAYS_BEFORE_STALE: 60
          DAYS_BEFORE_CLOSE: 30
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue has been automatically marked as stale because it has not had activity in the last ${{ env.DAYS_BEFORE_STALE }} days. Remove the stale label or comment or this issue will be closed in ${{ env.DAYS_BEFORE_CLOSE }} days. Thank you for your contributions."
          stale-pr-message: "This pull request has been automatically marked as stale because it has not had activity in the last ${{ env.DAYS_BEFORE_STALE }} days. Remove the stale label or comment or this pull request will be closed in ${{ env.DAYS_BEFORE_CLOSE }} days. Thank you for your contributions."
          stale-issue-label: "status:stale"
          stale-pr-label: "status:stale"
          days-before-stale: ${{ env.DAYS_BEFORE_STALE }}
          days-before-close: ${{ env.DAYS_BEFORE_CLOSE }}
          exempt-pr-labels: "dependencies,enhancement"
          remove-stale-when-updated: true
